version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    # restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DB_HOST=localhost
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_DB_LOCAL_PORT=3306
    ports:
      - 3306:3306
    logging:
      driver: none

  app:
    depends_on:
      - mysqldb
    links:
      - mysqldb
    build: .
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=HiaOQ4LgFW5
      - DB_NAME=fast_db
      - DB_PORT=3306
    volumes:
      - .:/myapp
    command: sh -c "npm install && npm start"

